#define M_UD -1			//undefined
#define M_ID 1			//ID
#define M_NUM 2			//NUM
#define M_SPC 3			//SPC
#define M_NL 4			//NL
#define M_ADD 5			//ADD
#define M_SUB 6			//SUB
#define M_PRINT 7		//PRINT
#define M_END 8			//END
#define M_SEMIC 9		//SEMIC
#define M_DEF 10		//DEFINE
#define M_BEGIN	11		//BEGIN
#define M_SET 12		//SET
#define M_READ 13		//READ
#define M_THEN 14		//THEN
#define M_WHILE 15		//while
#define M_ELSE 16		//else
#define M_DO 17			//do
#define M_EQ 18			//equal
#define M_LESS 19		//less
#define M_IF 20			//if
#define M_ENDOFFILE 0	//入力が尽きた場合
