#define M_UD -1			//undefined
#define M_ID 1			//ID
#define M_NUM 2			//NUM
#define M_SPC 3			//SPC
#define M_NL 4			//NL
#define M_ADD 5			//ADD
#define M_SUB 6			//SUB
#define M_PRINT 7		//PRINT
#define M_END 8			//END
#define M_SEMIC 9		//SEMIC
#define M_DEF 10		//DEFINE
#define M_ENDOFFILE 0	//入力が尽きた場合
